<div class="fp-special-sites">
	<h2 class="text-center">特設専門サイト</h2>
	<div class="small-up-1 medium-up-2 large-up-3 row">
		<div class="column column-inner"><a class="waves-effect link-external img" title="賠償金額が増額するケースが大半！交通事故の専門サイト" href="http://www.hiroshima-jiko.com/" target="_blank"><img src="<?php dtdsh_photon_img( '1494', 'src' ); ?>" alt="賠償金額が増額するケースが大半！交通事故の専門サイト" width="488" height="112" width="<?php dtdsh_photon_img( '1494', 'width' ); ?>" height="<?php dtdsh_photon_img( '1494', 'height' ); ?>"></a></div>
		<div class="column column-inner"><a class="waves-effect link-external img" title="女性弁護士3名所属！離婚・男女トラブルの専門サイト" href="http://www.hiroshima-rikon.com/" target="_blank"><img src="<?php dtdsh_photon_img( '1495', 'src' ); ?>" alt="女性弁護士3名所属！離婚・男女トラブルの専門サイト" width="488" height="112" width="<?php dtdsh_photon_img( '1495', 'width' ); ?>" height="<?php dtdsh_photon_img( '1495', 'height' ); ?>"></a></div>
		<div class="column column-inner"><a class="waves-effect link-external img" title="相続アドバイザーがサポート！相続・遺言の専門サイト" href="http://www.hiroshima-sozoku.com/" target="_blank"><img src="<?php dtdsh_photon_img( '1496', 'src' ); ?>" alt="相続アドバイザーがサポート！相続・遺言の専門サイト" width="488" height="112" width="<?php dtdsh_photon_img( '1496', 'width' ); ?>" height="<?php dtdsh_photon_img( '1496', 'height' ); ?>"></a></div>
		<div class="column column-inner"><a class="waves-effect link-external img" title="女性専用の相談もあります！借金問題の専門サイト" href="http://www.hiroshima-saimu.com/" target="_blank"><img src="<?php dtdsh_photon_img( '1497', 'src' ); ?>" alt="女性専用の相談もあります！借金問題の専門サイト" width="489" height="113" width="<?php dtdsh_photon_img( '1497', 'width' ); ?>" height="<?php dtdsh_photon_img( '1497', 'height' ); ?>"></a></div>
		<div class="column column-inner"><a class="waves-effect link-external img" title="手遅れになる前にご相談ください。刑事事件の専門サイト" href="http://www.hiroshima-keiji.com/" target="_blank"><img src="<?php dtdsh_photon_img( '1498', 'src' ); ?>" alt="手遅れになる前にご相談ください。刑事事件の専門サイト" width="488" height="112" width="<?php dtdsh_photon_img( '1498', 'width' ); ?>" height="<?php dtdsh_photon_img( '1498', 'height' ); ?>"></a></div>
		<div class="column column-inner"><a class="waves-effect link-external img black" title="不動産トラブルを弁護士が解決！不動産トラブルの専門サイト" href="http://www.hiroshima-fudosan.com/" target="_blank"><img src="<?php dtdsh_photon_img( '1499', 'src' ); ?>" alt="不動産トラブルを弁護士が解決！不動産トラブルの専門サイト" width="488" height="112" width="<?php dtdsh_photon_img( '1499', 'width' ); ?>" height="<?php dtdsh_photon_img( '1499', 'height' ); ?>"></a></div>
		<div class="column column-inner"><a class="waves-effect link-external img black" title="メリットが多い！顧問契約のススメ　企業法務の専門サイト" href="http://www.hiroshima-kigyo.com/" target="_blank"><img src="<?php dtdsh_photon_img( '1500', 'src' ); ?>" alt="メリットが多い！顧問契約のススメ　企業法務の専門サイト" width="488" height="112" width="<?php dtdsh_photon_img( '1500', 'width' ); ?>" height="<?php dtdsh_photon_img( '1500', 'height' ); ?>"></a></div>
		<div class="column column-inner"><a class="waves-effect link-external img black" title="破産は経営者の再出発！会社の破産・整理の専門サイト" href="http://www.hiroshima-hasan.com/" target="_blank"><img src="<?php dtdsh_photon_img( '1501', 'src' ); ?>" alt="破産は経営者の再出発！会社の破産・整理の専門サイト" width="488" height="112" width="<?php dtdsh_photon_img( '1501', 'width' ); ?>" height="<?php dtdsh_photon_img( '1501', 'height' ); ?>"></a></div>
		<div class="column column-inner"><a target="_blank" class="waves-effect link-external img" href="http://www.hiroshima-rosai.com/" title="賠償金が増額できる場合があります！労働災害の専門サイト"><img src="<?php dtdsh_photon_img( '2459', 'src' ); ?>" alt="賠償金が増額できる場合があります！労働災害の専門サイト" width="<?php dtdsh_photon_img( '2459', 'width' ); ?>" height="<?php dtdsh_photon_img( '2459', 'height' ); ?>"></a></div>
	</div>
</div>


